spring:
  application:
    name: ecommerce-microservice
  datasource:
    url: jdbc:mysql://my-db-instance.c1ee2wo4izzz.us-east-1.rds.amazonaws.com:3306/ecommerce
    username: admin
    password: "*Admin12345"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10      
server:
  port: 8080